import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../Components/Layout.js";

export default function Articles({ data }) {
  return (
    <Layout>
      <Head>
        <title>WebTech - articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Web technologies articles</h1>
      <p class="italic font-bold">
        This page fetch data from the client side, not good for SEO.
      </p>
      <ul>
        {data.map((article) => (
          <li key={article.slug}>
            <h2>
              <Link href={`/articles/${article.id}`}>{article.title}</Link>
            </h2>
            <p>{article.message}</p>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    "https://my-json-server.typicode.com/yGrouzelle/db-webtech/posts"
  );
  const db = await res.json();

  return {
    props: { data: db },
  };
};
