import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Layout from "../Components/Layout";

export default function Contacts() {
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);
  const onSubmit = async function (e) {
    e.preventDefault();
    const data = new FormData(e.target);
    const { error } = await supabase
      .from("contacts")
      .insert(Object.fromEntries(data), { returning: "minimal" });
    if (error) {
      setMessage("Sorry, an unexpected error occured.");
    } else {
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>Thank you for contacting us. We will get back to you promptly.</p>
        </div>
      );
    }
  };
  return (
    <Layout>
      <Head>
        <title>WebTech - contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="space-y-10">
        <div class="space-y-20">
          <h1 class="font-bold">Contact</h1>
          <div>
            <p>
              In order to contact us, please make sure you fill in the following
              form
            </p>
          </div>
        </div>
        <form class="relative h-32 w-32 space-y-10">
          <div>
            <div>
              <label>
                <span>First name</span>
                <input type="text" name="firstname" />
              </label>
            </div>
            <div>
              <label>
                <span>Last name</span>
                <input type="text" name="lastname" />
              </label>
            </div>
            <div>
              <label>
                <span>Email</span>
                <input type="text" name="email" />
              </label>
            </div>
            <div>
              <label>
                <span>Your message</span>
                <textarea name="message" />
              </label>
            </div>
            <div class="relative h-32 w-36">
              <div>
                <input
                  class="text-slate-100 bg-blue-400 rounded-md"
                  type="submit"
                  value="Send"
                />
              </div>
            </div>
          </div>
        </form>
      </div>
    </Layout>
  );
}
