import { useRouter } from 'next/router'
import { useContext } from 'react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import Layout from '../Components/Layout.js'
import {Context} from '../Components/UserContext'


export default function Login() {
  const { user } = useContext(Context)
  const router = useRouter()
  const supabaseClient = useSupabaseClient()
  console.log(user)
  if(user){ router.push('/user')
  console.log("connecte")
}
  return (
    <Layout>
      <Head>
        <title>WebTech - user signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth
        supabaseClient={supabaseClient}
        appearance={{ theme: ThemeSupa }}
        providers={['github']}
       />
    </Layout>
  )
}
